### ISSUE TITLE
Provide OXP topology json for integration testing.

### ISSUE THREAD

**Issue by YufengXin** [atlanticwave-sdx/kytos-sdx#42]
SDX-lC/SDX-Controller need the test files as inputs for unittest, in order to resolve issues.

**Comment by YufengXin** [comment]
paired with issue #43

**Comment by lmarinve** [comment]
Thank you for reporting the issue, Yufeng. We have provided a public URL that you can use to obtain the OXP topology JSON for integration testing. We are currently reviewing it to ensure that it is 100% accurate with the data model specification. If you come across any issues while testing, please do let us know as it will be very helpful for the whole test. curl -X 'GET' 'http://67.17.206.221/topology/1' -H 'accept:application/json'

**Comment by YufengXin** [comment]
The way unittest works is to have deterministic inputs to make assertions on deterministic output of functions. It won't work with a running instance under updating.

**Comment by italovalcy** [comment]
Hi,

The Topology JSON files were added to the datamodel repo and can be accessed here: 
- https://github.com/atlanticwave-sdx/datamodel/blob/main/src/sdx_datamodel/data/topologies/ampath_v2.json
- https://github.com/atlanticwave-sdx/datamodel/blob/main/src/sdx_datamodel/data/topologies/sax_v2.json
- https://github.com/atlanticwave-sdx/datamodel/blob/main/src/sdx_datamodel/data/topologies/zaoxi_v2.json
