### ISSUE TITLE
Test input request file 

### ISSUE THREAD

**Issue by YufengXin** [atlanticwave-sdx/kytos-sdx#43]
SDX-lC/SDX-Controller need the test files as inputs for unittest, in order to resolve issues.

paired with the topology jsons specified in issue #42

**Comment by lmarinve** [comment]
Thank you for reporting the issue #42, Yufeng. We have provided a public URL that you can use to obtain the OXP topology JSON for integration testing. We are reviewing it to ensure it is 100% accurate with the data model specification. If you come across any issues while testing, please do let us know, as it will be beneficial for the whole test. curl -X ‘GET’ ‘http://67.17.206.221/topology/1’ -H ‘accept:application/json’

**Comment by YufengXin** [comment]
This is about the paring request.

**Comment by italovalcy** [comment]
Hi,

Regarding the L2VPN requests for the SDX-Controller, examples can be found on the datamodel repo:
- https://github.com/atlanticwave-sdx/datamodel/blob/main/src/sdx_datamodel/data/requests/test-l2vpn-p2p-v2.json
- https://github.com/atlanticwave-sdx/datamodel/blob/main/src/sdx_datamodel/data/requests/test_request-amlight_zaoxi-p2p-v2.json

Regarding the L2VPN requests to be sent from SDX-LC to Kytos SDX Napp, examples can be found here:
- https://github.com/atlanticwave-sdx/kytos-sdx?tab=readme-ov-file#create-l2vpn-with-new-api
- https://github.com/atlanticwave-sdx/kytos-sdx?tab=readme-ov-file#edit-l2vpn-with-new-api
- https://github.com/atlanticwave-sdx/kytos-sdx?tab=readme-ov-file#delete-l2vpn-with-new-api
