### ISSUE TITLE
Provisioning function

### ISSUE THREAD

**Issue by YufengXin** [atlanticwave-sdx/kytos-sdx#47]
Right now sdx-lc calls the Eline endpoint with a made-up format for provisioning the breakdown in kotos domain.

Please provide implementation or usage instruction for the provisioning function.

**Comment by italovalcy** [comment]
> Right now sdx-lc calls the Eline endpoint with a made-up format for provisioning the breakdown in kotos domain.
> 
> Please provide implementation or usage instruction for the provisioning function.

Hi Yufeng, excellent!

We already provided that documentation on the README file, but here are some notes:

1) Currently SDX-LC is leveraging Kytos SDX Napp APIs to create L2VPN (Not mef_eline APIS!), this is an old API endpoint that was created exactly to make SDX-LC to work. SDX-LC should now evolve to leverage the new Kytos SDX APIs to create L2VPN, according to the new specs.

2) We also provided documentation on how to create, edit and delete L2VPN using the new API endpoints and new L2VPN provisioning APIs

3) the openapi schema also provides some information about this.
